### ISSUE TITLE
Windows build for Meson broken in CI

### ISSUE THREAD

**Issue by rgommers** [rgommers/scipy#116]
I've seen this a bunch of times now (e.g., in https://github.com/rgommers/scipy/runs/4842673552?check_suite_focus=true):

```
 [1511/1557] Compiling C++ object scipy/interpolate/_rbfinterp_pythran.cp39-win_amd64.pyd.p/meson-generated_..__rbfinterp_pythran.cpp.obj
In file included from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\core\include/numpy/ndarraytypes.h:4,
                 from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\core\include/numpy/ndarrayobject.h:12,
                 from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\core\include/numpy/arrayobject.h:5,
                 from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\pythran/pythonic/python/core.hpp:19,
                 from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\pythran/pythonic/include/types/int.hpp:19,
                 from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\pythran/pythonic/types/int.hpp:5,
                 from C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\pythran/pythonic/core.hpp:34,
                 from scipy/interpolate/_rbfinterp_pythran.cpp:1:
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\core\include/numpy/npy_common.h:185:20: warning: 'int _fseeki64(FILE*, long long int, int)' redeclared without dllimport attribute after being referenced with dll linkage
  185 | extern int __cdecl _fseeki64(FILE *, long long, int);
      |                    ^~~~~~~~~
C:\hostedtoolcache\windows\Python\3.9.9\x64\lib\site-packages\numpy\core\include/numpy/npy_common.h:186:26: warning: 'long long int _ftelli64(FILE*)' redeclared without dllimport attribute after being referenced with dll linkage
  186 | extern long long __cdecl _ftelli64(FILE *);
      |                          ^~~~~~~~~
```

The code from `npy_common.h` ([here](https://github.com/numpy/numpy/blob/9ba1440501d53d72ecce24ed207db62e3037d807/numpy/core/include/numpy/npy_common.h#L183)):
```C
/* mingw based on 3.4.5 has lseek but not ftell/fseek */
#if defined(__MINGW32__) || defined(__MINGW64__)
extern int __cdecl _fseeki64(FILE *, long long, int);
extern long long __cdecl _ftelli64(FILE *);
#endif
```
Pythran just has `ftell` ([here](https://github.com/serge-sans-paille/pythran/blob/52ec6f2b55c1fb4f72366154b7fd847b4aa28201/pythran/pythonic/types/file.hpp#L219)) and nothing else.

This seems to be an incompatibility between `numpy` and `mingw-w64` with the `long double` modifications. Cc @matthew-brett, @carlkl.

**Comment by rgommers** [comment]
> Is it possible that e.g. UCRT mingw does have `ftell`, so this guard is unnecessary?

Yes, very well possible. I didn't think about it deeply, just a general "mingw-w64 & long double" observation.

**Comment by carlkl** [comment]
I remember, i was going to send a numpy PR last year. This part of numpy defining _ftelli64 and _fseeki64 is outdated and not necessary anymore. Maybe it was for the _original mingw32_. However, almost nobody uses the _original mingw32 toolchain_ anymore. mingw-w64 is a fork of mingw32 and has both: 32 bit (also called mingw32) and the well known 64bit variant.

**Comment by matthew-brett** [comment]
@carlkl - can I help with the Numpy PR?

**Comment by rgommers** [comment]
Looks like it should be removed indeed, original mingw32 is indeed not worth supporting anymore.

One issue we will have is that the two conflicting definitions are in NumPy and Mingw-w64, both of which we cannot alter easily - so we're going to see this warning for a while. Important: I misread the build log, this is the last bit of output before an error, but _this itself is just a warning_. 

See https://stackoverflow.com/questions/11546403/importing-inline-functions-in-mingw for an explanation.


The actual broken part is unrelated (the parallel build just causes the log to be out of order) and due to ` cc1plus.exe: out of memory allocating 65536 bytes`. Which we can now fix, because the Cython build dependencies are fixed.

**Comment by rgommers** [comment]
Submitted a PR, so let's close this. I'll open a new issue if I can't get the Windows CI for Meson here to behave.
