### ISSUE TITLE
Investigate issue with `vsnprintf` and mingw-w64

### ISSUE THREAD

**Issue by rgommers** [rgommers/scipy#132]
This is a follow-up to gh-118. From the comments there:

>>> Thanks @carlkl, that's what I expected. It fixes `fprintf`, but not `vsnprintf`. All remaining warnings come from Cython-generated code. [gh-123](https://github.com/rgommers/scipy/pull/123) should take care of those. For GCC/Mingw I guess it means they should apply their fix also to the `v*nprintf` functions, and not just to `fprintf`.

>> Can you make a minimal standalone repro for the vsnprintf issue? Because when dealing with that, AFAIK it’s also affected by how you declare your own wrapper function that intercepts the varargs and calls vsnprintf. And I don’t see anything specifically relating to one but not the other function family in the gcc patch.

> We'll try. There's a level of indirection here, via CPython's `PyOS_snprintf`, so perhaps the problem is there.

Those warnings were silenced in https://github.com/rgommers/scipy/pull/123, however there's still a problem in one of Cython, CPython or Mingw-w64. It'd be nice to figure out where exactly, so we can remove the warning silencing and no one else has to deal with this in the future.

**Comment by carlkl** [comment]
I tested a fresh scipy checkout build with msys2 ucrt64 gcc-12.1 The `unknown conversion type character` warnings are all gone.
There are a lot of other warnings left. Should I open a different issue?

**Comment by rgommers** [comment]
> The `unknown conversion type character` warnings are all gone.

They should be, we fixed something in `f2py` and silenced the rest by this in `scipy/meson.build`:
```meson
    # Make fprintf("%zd") work (see https://github.com/rgommers/scipy/issues/118)
    add_global_arguments('-D__USE_MINGW_ANSI_STDIO=1', language: ['c', 'cpp'])
```
I think the "there's still a problem in one of Cython, CPython or Mingw-w64" statement is still true though - unless you see it's gone in another test case or after removing the above flag?

> There are a lot of other warnings left. Should I open a different issue?

Sure, that's always welcome.

**Comment by carlkl** [comment]
I get no warnings with `add_global_arguments('-D__USE_MINGW_ANSI_STDIO=0', language: ['c', 'cpp'])`. However, I use Msys2 ucrt64 mingw-w64 gcc-12.1. This toolchain contains a proposed patch for gcc-13. see https://www.mail-archive.com/gcc-patches@gcc.gnu.org/msg284696.html. This patch is not included in the rtools toolchain.

**Comment by carlkl** [comment]
I explicitly set `-D__USE_MINGW_ANSI_STDIO=0` instead of `1` to be sure, se yes _without_ `-D__USE_MINGW_ANSI_STDIO=1`.

**Comment by rgommers** [comment]
Great, thanks for confirming.
