### ISSUE TITLE
Using ninjatracing to profile build performance

### ISSUE THREAD

**Issue by rgommers** [rgommers/scipy#20]
This is quite a nice tool: https://github.com/nico/ninjatracing/blob/master/ninjatracing. It's Apache 2 licensed, so we cannot just vendor it. But usage is quite easy. Simply save that file as `ninjatracing.py` and run:
```
python tools/ninjatracing.py build/.ninja_log > trace.json
```
Then load `trace.json` in https://ui.perfetto.dev (or in Chrome) to obtain:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/98330/122240072-c390f880-cec1-11eb-8066-cedbae7b165b.png">

This allows exploring build performance. Also, shows the joys of building templated C++ (`pypocketfft`) and generated code. `pypocketfft` takes about 39 seconds, so that's a lower bound on the eventual SciPy build time we can expect.

It also shows what is wrong with rebuilds. Running `ninja -C build` twice in a row, the second time should be a no-op that completes in well under a second, however Cython code gets regenerated and rebuilt. I need to file a bug about this on the Meson issue tracker.

FYI @czgdp1807 (no urgent need for this, it was on my list to try for a little while and it's fun).

**Comment by czgdp1807** [comment]
Thanks @rgommers I will try looking into this. I think it depends on shifting the build system to `meson`, right?

**Comment by rgommers** [comment]
> It's Apache 2 licensed, so we cannot just vendor it.

I changed my mind on this one. The file doesn't get installed, so there's no problem adding it under `tools/`. Done now in the `meson` branch.

> I think it depends on shifting the build system to `meson`, right?

Yes, usage is:
```
meson setup build
ninja -C build  # generates log file
python ninjatracing.py build/.ninja_log > trace.json
```
And then load that trace file into the link above or into Chrome.

**Comment by rgommers** [comment]
`setuptools` has no such profiling facility indeed.

**Comment by rgommers** [comment]
`sparsetools` is a bit heavy .... that is what it is for now:

<img width="768" alt="image" src="https://user-images.githubusercontent.com/98330/122652250-1a0a6b00-d13e-11eb-8d9f-5fc2ea0a15d6.png">

**Comment by rgommers** [comment]
Now with `stats` and `special` included:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/98330/123549519-bdc0d000-d769-11eb-8964-0b264fc35f97.png">

**Comment by rgommers** [comment]
Ah, `ninja` is using too many threads by default. It chooses 26 on a 12-core Intel CPU, so `2*n + 2` with `n` the amount of physical cores.

If I build with `-j 12` (limit the number of threads to the number of physical cores), it's faster:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/98330/123549729-84d52b00-d76a-11eb-94b7-89b267820b41.png">

And with `-j 8`:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/98330/123549871-18a6f700-d76b-11eb-90fc-6650f2d1e6cb.png">

**Comment by rgommers** [comment]
Now that the build is 100% complete, let's add the final results.

8 jobs:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/98330/126068529-f23b4843-e4f0-45ab-84ab-317f672862b4.png">

12 jobs:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/98330/126068733-9a3a7558-b273-40eb-9a76-c16bab5c4cf8.png">

This is with GCC 9.3.0 and standard build settings (e.g., for C):
```
-fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g
-Wno-unused-function -Wno-conversion -Wno-unused-but-set-variable -Wno-misleading-indentation -Wno-incompatible-pointer-types -fPIC
```
on a 3 year old 12-core CPU (`Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz`).
