### ISSUE TITLE
Don't use `run_command` for building `cython --cplus` code

### ISSUE THREAD

**Issue by rgommers** [rgommers/scipy#25]
This is now done in `scipy.stats`, see https://github.com/rgommers/scipy/pull/23#issuecomment-868983390. It should be using `custom_target`, not `run_command`.

**Comment by czgdp1807** [comment]
Thanks for opening the issue. I will open a PR on Monday to fix this.

**Comment by rgommers** [comment]
It was bothering me, since on each `ninja` invocation it was rebuilding all those files. So I had a look, and it's mostly fixed in gh-27.

**Comment by rgommers** [comment]
fixed in gh-27
