### ISSUE TITLE
Removing use of deprecated NumPy C API from SciPy

### ISSUE THREAD

**Issue by rgommers** [rgommers/scipy#30]
SciPy uses the NumPy C API. Part of that C API is deprecated, and if an extension in SciPy still uses it then a build warning is emitted. The deprecated API uses direct field access (e.g. `x->data`) while the new API uses macros (e.g. `PyArray_DATA(x)`). We want to get rid of all deprecated API usage as much as possible.

For an example of what the warning looks like, see https://github.com/scipy/scipy/issues/5889 (reading that whole issue is quite instructive).

Examples of PRs fixing warnings: https://github.com/scipy/scipy/pull/14311, https://github.com/scipy/scipy/pull/4378. The latter PR also makes an adjustment to `setup.py` like (which would be good to do):
```python
from scipy._build_utils import numpy_nodepr_api

config.add_extension('extname', ..., **numpy_nodepr_api)
```

To find modules which are using the deprecated API, search `meson.build` files for `Wno-cpp` (the flag that suppresses the warning). E.g. right now, searching with `ripgrep`, I see:
```bash
$ rg Wno-cpp
scipy/integrate/meson.build
86:    c_args: '-Wno-cpp',  # TODO: replace with numpy_nodepr_api

scipy/optimize/meson.build
172:             '-Wno-cpp', '-Wno-int-in-bool-context', 

scipy/sparse/sparsetools/meson.build
21:  cpp_args : '-Wno-cpp',  # suppress numpy deprecation warnings

scipy/stats/meson.build
76:  cpp_args: '-Wno-cpp',  # TODO: replace with numpy_nodepr_api

scipy/spatial/meson.build
27:  c_args: '-Wno-cpp',
57:  cpp_args: cpp_args + ['-Wno-cpp'], # TODO: replace with numpy_nodepr_api
65:  c_args: '-Wno-cpp', # TODO: replace with numpy_nodepr_api

scipy/spatial/transform/meson.build
3:  c_args: '-Wno-cpp', # TODO: replace with numpy_nodepr_api
```
Important to know:
- C code can and should all be fixed
- Cython code may be problematic, fix only if the code doesn't get uglier (see discussion in https://github.com/scipy/scipy/pull/10840 - that PR stalled, some of the code may be reusable)

An efficient way of working is likely something like:
1. Search for the `-Wno-cpp` flag
2. Pick a module to work on, change the `'-Wno-cpp'` flag to `numpy_nodepr_api`
3. Run the build with `ninja -C build`, you should now see ~the warnings~ errors 
4. Update the C code, then rerun `ninja -C build`
5. Once things work, copy the changes to a new branch based on `upstream/master`
6. Add the `**nodepr_api` change to `setup.py`
7. Send a PR to SciPy (one PR per module seems good, if there's only a couple of code changes maybe combining 2-3 modules makes sense).

Cc @Smit-create

**Comment by Smit-create** [comment]
Should I now start working on fixing deprecated C API?

**Comment by Smit-create** [comment]
Should this be removed now?
https://github.com/rgommers/scipy/blob/bd217f6b2996fd145e93d036ff3cd0e3f4db5f29/scipy/integrate/meson.build#L84-L87

It seems to be fixed in https://github.com/scipy/scipy/pull/14268

The build doesn't produce any warnings now.

**Comment by rgommers** [comment]
> Should this be removed now?

Yes, good catch!

> Should I now start working on fixing deprecated C API?

That sounds good. I also recommend spending some time on working through the Python and NumPy C API tutorials - it will be quite helpful for several topics you may be working on:
- https://docs.python.org/3/extending/index.html
- https://numpy.org/devdocs/user/c-info.how-to-extend.html

**Comment by Smit-create** [comment]
I think we can also remove this:
https://github.com/rgommers/scipy/blob/bd217f6b2996fd145e93d036ff3cd0e3f4db5f29/scipy/interpolate/meson.build#L153-L155

The build passed without any warnings.

**Comment by rgommers** [comment]
> The build passed without any warnings.

It doesn't for me, all flags are necessary.

**Comment by Smit-create** [comment]
> It doesn't for me, all flags are necessary.

Oops, Sorry!

So here `pythran` is generating `.cpp` file from `/interpolate/_rbfinterp_pythran.py` by itself. When using `numpy_nodepr_api` here raises deprecated warning:
```
In file included from /home/smit/anaconda3/envs/scipy-dev/lib/python3.9/site-packages/pythran/pythonic/include/types/int.hpp:19,
                 from /home/smit/anaconda3/envs/scipy-dev/lib/python3.9/site-packages/pythran/pythonic/types/int.hpp:5,
                 from /home/smit/anaconda3/envs/scipy-dev/lib/python3.9/site-packages/pythran/pythonic/core.hpp:27,
                 from ../scipy/interpolate/_rbfinterp_pythran.cpp:1:
/home/smit/anaconda3/envs/scipy-dev/lib/python3.9/site-packages/pythran/pythonic/python/core.hpp:17: warning: "NPY_NO_DEPRECATED_API" redefined
   17 | #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
      | 
<command-line>: note: this is the location of the previous definition
```
This is basically from here: https://github.com/serge-sans-paille/pythran/blob/master/pythran/pythonic/python/core.hpp

So, doesn't require any fix in `interpolate` right?

**Comment by rgommers** [comment]
That sounds right. I didn't realize Pythran defined `NPY_NO_DEPRECATED_API`, but that's good - we don't have to do it then.

**Comment by Smit-create** [comment]
Presently, I get following modules that use `Wno-cpp`. Let's keep a track of completed ones:
```
$ rg Wno-cpp
scipy/optimize/meson.build
172:             '-Wno-cpp', '-Wno-int-in-bool-context', 

scipy/sparse/sparsetools/meson.build
21:  cpp_args : '-Wno-cpp',  # suppress numpy deprecation warnings

scipy/integrate/meson.build
86:    c_args: '-Wno-cpp',  # TODO: replace with numpy_nodepr_api

scipy/signal/meson.build
33:             '-Wno-cpp', '-Wno-int-in-bool-context',
49:             '-Wno-cpp', '-Wno-int-in-bool-context',
89:  c_args: ['-Wno-cpp'],  # TODO: replace with numpy_nodepr_api

scipy/stats/meson.build
76:  cpp_args: '-Wno-cpp',  # TODO: replace with numpy_nodepr_api

scipy/spatial/transform/meson.build
3:  c_args: '-Wno-cpp', # TODO: replace with numpy_nodepr_api

scipy/spatial/meson.build
27:  c_args: '-Wno-cpp',
57:  cpp_args: cpp_args + ['-Wno-cpp'], # TODO: replace with numpy_nodepr_api
65:  c_args: '-Wno-cpp', # TODO: replace with numpy_nodepr_api

scipy/interpolate/meson.build
122:  c_args: ['-Wno-cpp', '-Wno-maybe-uninitialized'], # TODO: Replace with numpy_nodepr_api
155:             '-Wno-cpp', '-Wno-int-in-bool-context',

```
- [ ] `optimize`
- [ ] `sparse`
- [x] `integrate`
- [ ] `signal`
- [ ] `stats`
- [ ] `spatial`
- [x] `interpolate`

**Comment by Smit-create** [comment]
@rgommers Can you please rebase `meson` branch with scipy `master` branch so that I can push the warnings that have been fixed?

**Comment by rgommers** [comment]
Sure, done

**Comment by rgommers** [comment]
This is all done except for Cython code, which we don't want to touch right now. So let's close this. Thanks @Smit-create!
