### ISSUE TITLE
Update Meson build files for C++ Cython support

### ISSUE THREAD

**Issue by rgommers** [rgommers/scipy#66]
### Please describe your issue.

https://github.com/mesonbuild/meson/pull/9017 added support in Meson master to target C++ when using `add_extension('somefile.pyx')`. This is much nicer than using `custom_target` for the `.pyx` to `.cpp` step, so we should update all build files where this is current done to use the new functionality.

**Comment by dhruv9vats** [comment]
I would like to take this up if that's okay.

**Comment by rgommers** [comment]
Sure, please go for it @dhruv9vats!

**Comment by dhruv9vats** [comment]
From what I understand, on [this](https://github.com/rgommers/scipy/blob/03ac3e89b0d081ebe5c3de5624a1a60f7ee29bb5/scipy/special/meson.build#L378) line, the following code snippet:
```meson
_ufuncs_cxx_cy = custom_target('_ufuncs_cxx_cy',
  output : '_ufuncs_cxx.cpp',
  input : cython_special[2],
  command : [cython, '--cplus', '-3', '--fast-fail', '@INPUT@']
)

py3.extension_module('_ufuncs_cxx',
  [ufuncs_cxx_sources, _ufuncs_cxx_cy, _cython_tree],
  cpp_args : [numpy_nodepr_api, use_math_defines],
  include_directories: [inc_np, '../_lib', '../_build_utils/src'],
  dependencies : [py3_dep, npymath_lib, _ufuncs_pxi_pxd_dep],
  install : true,
  subdir : 'scipy/special'
)
```
changes to:

```meson
py3.extension_module('_ufuncs_cxx',
  [ufuncs_cxx_sources, cython_special[2], _cython_tree], # Change one input, which now points to a .pyx file
  cpp_args : [numpy_nodepr_api, use_math_defines],
  include_directories: [inc_np, '../_lib', '../_build_utils/src'],
  dependencies : [py3_dep, npymath_lib, _ufuncs_pxi_pxd_dep],
  override_options : ['cython_language=cpp'],  # The newly added functionality
  install : true,
  subdir : 'scipy/special'
)
```

This is what we are basically trying to accomplish, right? 
But _only_ where there is a conversion between a `.pyx` to a `.cpp` file using cython? (That is, not dealing with `.pyx` to `.c` or `.py` to `.cpp` conversions which use pythran, but exclusively `.pxy` to `.cpp` which use cython.

Sorry if I'm overlooking something obvious.

**Comment by rgommers** [comment]
Yes, that sounds exactly right. Searching the code base for `cython, '--cplus'` should give you all relevant extensions.
